CREATE TABLE [dbo].[TBALTERNATIVA] (
    [NUMERO]         INT           IDENTITY (1, 1) NOT NULL,
    [QUESTAO_NUMERO] INT           NOT NULL,
    [LETRA]          VARCHAR (10)  NOT NULL,
    [DESCRICAO]      VARCHAR (300) NOT NULL,
    PRIMARY KEY CLUSTERED ([NUMERO] ASC),
    CONSTRAINT [FK_TBALTERNATIVA] FOREIGN KEY ([QUESTAO_NUMERO]) REFERENCES [dbo].[TBQUESTAO] ([NUMERO])
);

