CREATE TABLE [dbo].[TBQUESTAO] (
    [NUMERO]            INT           IDENTITY (1, 1) NOT NULL,
    [ENUNCIADO]         VARCHAR (300) NOT NULL,
    [RESPOSTA]          VARCHAR (10)  NOT NULL,
    [MATERIA_NUMERO]    INT           NOT NULL,
    [DISCIPLINA_NUMERO] INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([NUMERO] ASC),
    CONSTRAINT [FK_TBQUESTAO_DISCIPLINA] FOREIGN KEY ([DISCIPLINA_NUMERO]) REFERENCES [dbo].[TBDisciplina] ([Numero]),
    CONSTRAINT [FK_TBQUESTAO_MATERIA] FOREIGN KEY ([MATERIA_NUMERO]) REFERENCES [dbo].[TBMateria] ([Numero])
);

