CREATE TABLE [dbo].[TBTESTE] (
    [NUMERO]            INT           IDENTITY (1, 1) NOT NULL,
    [TITULO]            VARCHAR (300) NOT NULL,
    [DATACRIACAO]       DATETIME      NOT NULL,
    [MATERIA_NUMERO]    INT           NOT NULL,
    [DISCIPLINA_NUMERO] INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([NUMERO] ASC),
    CONSTRAINT [FK_TBTESTE_DISCIPLINA] FOREIGN KEY ([DISCIPLINA_NUMERO]) REFERENCES [dbo].[TBDisciplina] ([Numero]),
    CONSTRAINT [FK_TBTESTE_MATERIA] FOREIGN KEY ([MATERIA_NUMERO]) REFERENCES [dbo].[TBMateria] ([Numero])
);

